# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Add Two Numbers
#'
#' Return the sum of two numbers.
#' @param x numeric; the first number
#' @param y numeric; the second number
#' @export
add_cpp <- function(x, y) {
    .Call(`_pkgrcpp_add_cpp`, x, y)
}

#' Sums a List of Numbers
#'
#' Return the sum of a list of numbers.
#' @param x numeric vector; a list of numbers to be summed
#' @export
sumC <- function(x) {
    .Call(`_pkgrcpp_sumC`, x)
}

# Register entry points for exported C++ functions
methods::setLoadAction(function(ns) {
    .Call(`_pkgrcpp_RcppExport_registerCCallable`)
})
